/**
 * @flow
 * Created by Dima Portenko on 06.10.2020
 */

export const NAVIGATION_CATEGORIES_ROUTE = 'NAVIGATION_CATEGORIES_ROUTE';
export const NAVIGATION_PRODUCTS_ROUTE = 'NAVIGATION_PRODUCTS_ROUTE';
